export const copy = {
  title: "日陰ナビ",
  subtitle: "渋谷区 · 徒歩",
  nightBadge: "夜間",
  legendShortest: "最短",
  legendShade: "日陰",
  waterToggle: "給水スポット",
  s0: "地図をタップして出発地点を選んでください",
  s0sub: "対象は渋谷区内の徒歩ルートです",
  peekS1: "次に到着地点をタップしてください",
  s1: "出発が決まりました。次に到着地点をタップしてください",
  redoOrigin: "出発をやり直す",
  s2: "出発・到着が決まりました",
  search: "ルートを探す",
  reset: "やり直す",
  sameRoute: "同じルートです",
  continuousSun: (label: string) => `連続直射日光 最大${label}`,
  longer: (m: number) => `日陰ルートは ${m}m 長いです`,
  muchLonger: "日陰ルートは最短よりかなり長いです",
  nightOnly: "夜間のため日陰ルートはありません",
  loadingMap: "読み込み中",
  loadingRoute: "ルートを計算しています",
  nightShade: "夜間のため日陰を計算しません",
  useLocation: "現在地を出発にする",
  close: "閉じる",
  outsideHint: "渋谷区内の2点を指定してください",
  attribution:
    "地図: 国土地理院 / 建物: Project PLATEAU（国土交通省） / 道路: © OpenStreetMap contributors / 対象: 渋谷区 · 徒歩のみ",
  errors: {
    outside: "渋谷区内の2点を指定してください",
    too_far: "3km以内で指定してください",
    snap: "歩ける道の近くを選んでください",
    disconnected: "この2点を歩くルートが見つかりません",
    server: "しばらくしてからもう一度お試しください",
  },
};
